### ISSUE TITLE
Entity/Chunk Tracker Imploded

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#51]
### Spark link

N/A

### Stack trace

```
[17:46:37] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos@11aa5568, suppressing error
java.lang.IllegalStateException: Chunk should exist at [-281, 325]
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedPlayer.removeCallback(NearbyPlayers.java:207) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedPlayer.removeCallback(NearbyPlayers.java:183) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.SingleUserAreaMap.update(SingleUserAreaMap.java:226) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers.tickPlayer(NearbyPlayers.java:83) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.server.ServerEntityLookup.entitySectionChangeCallback(ServerEntityLookup.java:64) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup.moveEntity(EntityLookup.java:575) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup$EntityCallback.onMove(EntityLookup.java:1067) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:4952) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.Entity.setPos(Entity.java:876) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.Entity.move(Entity.java:1238) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1524) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:75) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:161) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1683) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:200) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1660) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1653) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:145) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1611) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1619) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1459) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[?:1.21.1-DEV-cfc54fd]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

```
[17:46:39] [minecraft:nations_ng4_world/ERROR]: Failed to handle packet for /89.89.6.153:64552
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:973) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.network.Connection.tick(Connection.java:667) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.level.ServerLevel.tickThread(ServerLevel.java:700) ~[?:1.21.1-DEV-cfc54fd]
	at io.github.dueris.canvas.thread.TickLoopThread.run(TickLoopThread.java:119) ~[?:1.21.1-DEV-cfc54fd]
Caused by: java.lang.IllegalStateException: Does not contain player ServerPlayer['jjkay03'/77, uuid='86408a0b-54e3-4e48-8bb0-104fe4e9116d', l='ServerLevel[nations_ng4_world]', x=-4700.37, y=74.84, z=4656.00, cpos=[-294, 291], tl=52776, v=true](jjkay03 at -4700.366956083272,74.84118579598416,4656.0027390289115)
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedChunk.removePlayer(NearbyPlayers.java:173) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedPlayer.removeCallback(NearbyPlayers.java:210) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedPlayer.removeCallback(NearbyPlayers.java:183) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.SingleUserAreaMap.update(SingleUserAreaMap.java:226) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers.tickPlayer(NearbyPlayers.java:83) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.server.ServerEntityLookup.entitySectionChangeCallback(ServerEntityLookup.java:64) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup.moveEntity(EntityLookup.java:575) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup$EntityCallback.onMove(EntityLookup.java:1067) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:4952) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.Entity.setPos(Entity.java:876) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.Entity.move(Entity.java:1238) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:3175) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:3109) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.player.Player.travel(Player.java:1720) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.level.ServerPlayer.travel(ServerPlayer.java:1932) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3641) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.player.Player.aiStep(Player.java:613) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3289) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.world.entity.player.Player.tick(Player.java:317) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:887) ~[?:1.21.1-DEV-cfc54fd]
	... 4 more
```

```
[17:46:39] [minecraft:nations_ng4_world/INFO]: jjkay03 lost connection: Internal server error
[17:46:39] [minecraft:nations_ng4_world/INFO]: [voicechat] Disconnecting client jjkay03
[17:46:39] [minecraft:nations_ng4_world/WARN]: java.lang.IllegalStateException: Does not contain player ServerPlayer['jjkay03'/77, uuid='86408a0b-54e3-4e48-8bb0-104fe4e9116d', l='ServerLevel[nations_ng4_world]', x=-4702.40, y=74.85, z=4661.73, cpos=[-294, 291], tl=52777, v=false, removed=UNLOADED_WITH_PLAYER](jjkay03 at -4702.404419307708,74.84521659262637,4661.7276065683245)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedChunk.removePlayer(NearbyPlayers.java:173)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedPlayer.removeCallback(NearbyPlayers.java:210)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedPlayer.removeCallback(NearbyPlayers.java:183)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at ca.spottedleaf.moonrise.common.misc.SingleUserAreaMap.removeFromOld(SingleUserAreaMap.java:60)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at ca.spottedleaf.moonrise.common.misc.SingleUserAreaMap.remove(SingleUserAreaMap.java:244)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers.removePlayer(NearbyPlayers.java:71)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.server.ServerEntityLookup.removeEntityCallback(ServerEntityLookup.java:78)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup$EntityCallback.onRemove(EntityLookup.java:1088)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:5073)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.world.entity.Entity.remove(Entity.java:798)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:768)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.world.entity.player.Player.remove(Player.java:1591)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.server.level.ServerLevel.removePlayerImmediately(ServerLevel.java:1798)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:656)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:594)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2186)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2166)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2153)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.network.Connection.handleDisconnection(Connection.java:939)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at net.minecraft.server.level.ServerLevel.tickThread(ServerLevel.java:718)
[17:46:39] [minecraft:nations_ng4_world/WARN]: 	at io.github.dueris.canvas.thread.TickLoopThread.run(TickLoopThread.java:119)
```

```
[17:46:39] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundAcceptTeleportationPacket@22f94911, suppressing error
java.lang.IllegalStateException: Does not contain player ServerPlayer['___zency___'/438, uuid='9d13703c-c82e-4b02-a742-b72e16b21732', l='ServerLevel[nations_ng4_world]', x=-4632.76, y=70.84, z=4687.83, cpos=[-290, 292], tl=5385, v=true](___zency___ at -4632.764567638528,70.83999997377396,4687.832182471865)
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedChunk.removePlayer(NearbyPlayers.java:173) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedPlayer.removeCallback(NearbyPlayers.java:210) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers$TrackedPlayer.removeCallback(NearbyPlayers.java:183) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.SingleUserAreaMap.update(SingleUserAreaMap.java:226) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.misc.NearbyPlayers.tickPlayer(NearbyPlayers.java:87) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader.updatePlayer(RegionizedPlayerChunkLoader.java:210) ~[?:1.21.1-DEV-cfc54fd]
	at ca.spottedleaf.moonrise.common.util.ChunkSystem.updateMaps(ChunkSystem.java:160) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.level.ChunkMap.move(ChunkMap.java:893) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.level.ServerChunkCache.move(ServerChunkCache.java:676) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAcceptTeleportPacket(ServerGamePacketListenerImpl.java:772) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.network.protocol.game.ServerboundAcceptTeleportationPacket.handle(ServerboundAcceptTeleportationPacket.java:33) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.network.protocol.game.ServerboundAcceptTeleportationPacket.handle(ServerboundAcceptTeleportationPacket.java:15) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:161) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1683) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:200) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1660) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1653) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:145) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1611) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1619) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1459) ~[?:1.21.1-DEV-cfc54fd]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[?:1.21.1-DEV-cfc54fd]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Actions to reproduce (if known)

Not sure what caused it but we had about 40 players online spawning in one world then warping to another world via a warp sign.

### Canvas version

Forgot to run /version before switching to purpur but it's the latest jar (615)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

### Other

I believe I included all the variants of the error in the order they appeared
I have included the section of the latest log starting just before everything imploded.

[latest (1).log](https://github.com/user-attachments/files/17524626/latest.1.log)

**Comment by Dueris** [comment]
fixed
